---
- name: Play 03. DB 서버 설정
  hosts: dbservers
  gather_facts: true
  tasks:
    - name: 3.1) 변수 포함
      include_vars: paths.yml

    - name: 3.2) 원격 디렉토리 생성
      ansible.builtin.file:
        path: "{{ paths.dbpath }}"
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'
      register: output

    - name: 3.3) 디버깅 메세지
      ansible.builtin.debug:
        var: output.path
