---
- name: Restore factcheck.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) 방화벽 등록 제거
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 2) services are stopped
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: 3) Remove index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) Remove package - httpd
      ansible.builtin.yum:
        name: httpd
        state: absent
