---
# tasks file for roles/rollback_playbook
# --------------------------------------- #
# 2) (include_role) 서버 복원 작업
# 2.1) 방화벽 포트 제거
#  - http
#  - https
# 2.2) 서비스 종료
#  - httpd
#  - firewalld
# 2.3) 웹 서비스 설정 삭제
#  - /etc/httpd/conf.d/vhost.conf
#  - /var/www/html/index.html
#  - /var/www/vhosts
# 2.4) 패키지 삭제
#  - httpd
#  - mod_ssl
# --------------------------------------- #
- name: 2.1) 방화벽 포트 제거
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
  loop: "{{ fw_rules }}"
  ignore_errors: true

- name: 2.2) 서비스 종료
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ services }}"
  ignore_errors: true

- name: 2.3) 웹 서비스 설정 삭제
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ web_settings }}"

- name: 2.4) 패키지 삭제
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
    state: absent
