---
- name: Restore intranet.yml
  hosts: web1.example.com
  tasks:
    # ----------------------------------------------- #
    # 1) 방화벽 삭제 - http
    # 2) 서비스 중지 - httpd.service
    # 3) 웹서버 설정 파일 삭제 - /var/www/html/index.html
    # 4) 패키지 삭제 - httpd
    # ----------------------------------------------- #

    - name: 1) 방화벽 삭제 - http
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 2) 서비스 중지 - (systemd) httpd.service
      ansible.builtin.systemd:
        name: httpd
        state: stopped
        enabled: false

    - name: 3) 웹서버 설정 파일 삭제 - (file) /var/www/html/index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제 - (dnf) httpd
      ansible.builtin.dnf:
        name:
          - httpd
        state: absent
