---
# Task File:
- name: 1.1) 서비스 중지 - {{ service }}
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: false

- name: 1.2) 패키지 삭제 - {{ packages }}
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: absent

- name: 1.3) 설정 파일 삭제 - {{ files }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files }}"
